version: "3.9"

services:
  tts-api:
    build: .
    container_name: tts-api
    expose:
      - 8000
  tts-proxy:
    container_name: tts-proxy
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - tts-api
  tts-frontend:
    build: frontend
    container_name: tts-ui
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
