version: "3.9"

services:
  tts-api:
    build: .
    container_name: tts-api
  tts-proxy:
    container_name: tts-proxy
    build: nginx
    restart: always
    depends_on:
      - tts-api
  tts-ui:
    build: frontend
    container_name: tts-ui
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
