version: "3.1"

services:
  tts-api:
    build: .
    container_name: tts-api
    expose:
      - 8080 # for uwsgi
      # - 5000 # for ui
    ports:
      - 5000:5000
    # networks:
    #   - tts-net
  # tts-nginx:
  #   build: ./nginx
  #   container_name: tts-nginx
  #   ports:
  #     - 80:80
  tts-frontend:
    build: ./frontend
    container_name: tts-ui
    ports:
      - 3000:3000
    # expose:
    #   - 8080
    # networks:
    #   - tts-net

# networks:
#   tts-net:
#     driver: bridge
